#cloud-config
users: # Liste der Benutzer, die konfiguriert werden sollen
  - name: ubuntu # Der Name des Benutzers ist "ubuntu"
    sudo: ALL=(ALL) NOPASSWD:ALL # Sudo-Rechte ohne Passwort abzufragen
    groups: users, admin # Wird zu den Gruppen users und adnim hinzugefügt
    home: /home/ubuntu # Home-Verzeichnis des users
    shell: /bin/bash # Bash als Shell
    ssh_authorized_keys: # Authorisierte ssh-keys
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key # SSH-Key

package_update: true
package_upgrade: true
packages:
  - apache2
  - php
  - libapache2-mod-php
  - php-mysqli
  - git
  - adminer

write_files:
  - path: /var/www/html/db.php
    permissions: "0644"
    content: |
      <?php
      //database
      $servername = "172.31.16.60";
      $username = "admin";
      $password = "password";
      $dbname = "mysql";
      // Create connection
      $conn = new mysqli($servername, $username, $password, $dbname);
      // Check connection
      if ($conn->connect_error) {
          die("Connection failed: " . $conn->connect_error);
      }
      $sql = "select Host, User from mysql.user;";
      $result = $conn->query($sql);
      while($row = $result->fetch_assoc()){
          echo($row["Host"] . " / " . $row["User"] . "<br />");
      }
      ?>

  - path: /var/www/html/info.php
    permissions: "0644"
    content: |
      <?php
      // Show all information, defaults to INFO_ALL
      phpinfo();
      ?>

runcmd:
  - sudo a2enmod rewrite
  - sudo a2enconf adminer
  - sudo systemctl restart apache2
