#cloud-config
users: # Liste der Benutzer, die konfiguriert werden sollen
  - name: ubuntu # Der Name des Benutzers ist "ubuntu"
    sudo: ALL=(ALL) NOPASSWD:ALL # Sudo-Rechte ohne Passwort abzufragen
    groups: users, admin # Wird zu den Gruppen users und adnim hinzugefügt
    home: /home/ubuntu # Home-Verzeichnis des users
    shell: /bin/bash # Bash als Shell
    ssh_authorized_keys: # Authorisierte ssh-keys
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key # SSH-Key

package_update: true
packages:
  - mariadb-server
 
runcmd:
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf # Der Befehl ersetzt alle Vorkommen von 127.0.0.1 durch 0.0.0.0 in der Datei 50-server.cnf. sed ist zum ersetzen.
  - echo "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;" | mysql -u root
  - sudo systemctl restart mariadb
